Release/ex2 correcao
aLiviaMs/Sprint01-HelpperOrigins pull request #6
Opened 2021-10-29 19:33 UTC by aLiviaMs

Correção realizada.

2021-10-29 19:36 UTC, aLiviaMs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 2](https://trello.com/c/uCgSxpdI/32-exerc%C3%ADcio-2)

2021-11-02 16:33 UTC, LuizJarduli approved these changes

2021-11-06 12:08 UTC, LuizJarduli requested changes

2021-11-06 12:08 UTC, LuizJarduli commented on Exercicio02/script.ts
> +            list.splice(index, 1);
o `splice` modificando o a lista original fere os princípios da programação funcional, onde os parâmetros devem se manter imutáveis ao longo da função. Uma alternativa é usar somente o `filter` , que retorna um novo `Array` não modificando a original

2021-11-06 12:08 UTC, LuizJarduli commented on Exercicio02/script.ts
> +    const index = list.findIndex(person => person["id"] === id);
importante tipar as variáveis, isso vale para todo o código

2021-11-10 22:45 UTC, merged