ex3 review
aLiviaMs/Sprint01-HelpperOrigins pull request #8
Opened 2021-10-29 23:53 UTC by aLiviaMs

2021-10-29 23:55 UTC, aLiviaMs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 3](https://trello.com/c/RdJo47FX/33-exerc%C3%ADcio-3)

2021-10-29 23:55 UTC, aLiviaMs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 3](https://trello.com/c/RdJo47FX/33-exerc%C3%ADcio-3)

2021-11-06 12:03 UTC, LuizJarduli requested changes

2021-11-06 12:03 UTC, LuizJarduli commented on ex3Funcional.ts
> +
ao invés de declarar um `Arrays` para logo embaixo ter um return, você poderia retornar `return [maxNumber, minNumber, meanNumber(list)]`. Evitaria criar uma nova variável

2021-11-11 00:59 UTC, closed without merging