Ex4
aLiviaMs/Sprint01-HelpperOrigins pull request #9
Opened 2021-10-31 14:11 UTC by aLiviaMs

2021-10-31 14:12 UTC, aLiviaMs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 4](https://trello.com/c/ZWrEQEw3/34-exerc%C3%ADcio-4)

2021-11-01 04:39 UTC, Felipe-Faria-Helpper requested changes

2021-11-01 04:39 UTC, Felipe-Faria-Helpper commented on Exercicio04/ex4.ts
> +    const tableTrs = list.map(createTable);
Tipar essa const

2021-11-01 04:39 UTC, Felipe-Faria-Helpper commented on Exercicio04/ex4.ts
> +    const updateForm = document.createElement("form");
Tipar essa const e todas as declaradas abaixo

2021-11-01 04:39 UTC, Felipe-Faria-Helpper commented on Exercicio04/ex4.ts
> +    console.log(updateForm);
Esses console.logs são necessários?

2021-11-01 04:39 UTC, Felipe-Faria-Helpper commented on Exercicio04/ex4.ts
> +    const listRemoveId = list.filter((person: Person) => person.id !== id);
Tipar const

2021-11-01 04:39 UTC, Felipe-Faria-Helpper commented
O exercício está ótimo, favor só atentar com as tipagens.

2021-11-11 00:59 UTC, closed without merging